version: "3"
services:
  postgres:
    build: ./db
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build: ./api
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres